### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by jamescridland** [rssblue/tools#1]
Happily, this system also shares a bit of a dislike of the Irish pop band, who sang songs like "Leave me breathless" and, um, the others in the late 1990s.

I hate to say: I think you'll have a lot of CORS errors with this tester though. Might be good to catch this and remind us what the CORS header should say; and then proxy the RSS call if it's failed.

![Screenshot_20221129-170954](https://user-images.githubusercontent.com/231941/204462422-43232252-b359-4b24-ada2-fe416a55a0bb.png)

**Comment by joksas** [comment]
Thank you, James! I agree. I really didn't want to do a proxy server myself, but I've ended up implementing one...

Please let me know if the [new interface](https://tools.rssblue.com/validator?url=https://podnews.net/rss) is more intuitive and also if you see any errors. Personally, I can fetch <https://podnews.net/rss> both without and with the RSS Blue proxy turned on.

**Comment by joksas** [comment]
@jamescridland, I've added the following message for feed hosts:

![image](https://user-images.githubusercontent.com/46974359/205264198-6be146d7-844e-4898-a586-121b06458ca0.png)
